# create_file.yml
- name: Create a dynamic file
  hosts: all
  become: yes
  vars:
    file_name: "{{ file_name | default('/tmp/default.txt') }}"
  tasks:
    - name: Create file
      file:
        path: "{{ file_name }}"
        state: touch
